
Mon, 29 Apr 2019 21:03:22 GMT

COMMAND LINE:
/usr/bin/graalpython fasta.graal-3.graal 2500000

PROGRAM FAILED 


PROGRAM OUTPUT:

Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
Traceback (most recent call last):
  File "fasta.python3-3.python3", line 138, in <module 'fasta.python3-3.python3'>
  File "fasta.python3-3.python3", line 127, in main
  File "fasta.python3-3.python3", line 52, in repeat_fasta
TypeError: got an unexpected keyword argument 'encoding'
