
Mon, 07 Sep 2015 11:14:03 GMT

COMMAND LINE:
/usr/bin/pypy fibonacci.pypy 1000000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "fibonacci.pypy", line 8, in <module>
    print fib(int(sys.argv[1]))
  File "fibonacci.pypy", line 6, in fib
    return (numpy.matrix('1 1; 1 0', numpy.dtype('object')) ** n).tolist()[0][1]
  File "/opt/pypy/site-packages/numpy/matrixlib/defmatrix.py", line 354, in __pow__
    return matrix_power(self, other)
  File "/opt/pypy/site-packages/numpy/matrixlib/defmatrix.py", line 196, in matrix_power
    Z = N.dot(Z, Z)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
