
Wed, 21 Dec 2016 14:14:43 GMT

COMMAND LINE:
/usr/bin/micropython meteor.micropython-2.micropython 2098

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "meteor.micropython-2.micropython", line 189, in <module>
  File "meteor.micropython-2.micropython", line 186, in solve
  File "meteor.micropython-2.micropython", line 141, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 141, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 141, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 141, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 141, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 141, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 141, in solveCell
  File "meteor.micropython-2.micropython", line 141, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 141, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 131, in solveCell
  File "meteor.micropython-2.micropython", line 141, in solveCell
  File "meteor.micropython-2.micropython", line 128, in solveCell
  File "meteor.micropython-2.micropython", line 166, in addSolutions
MemoryError: memory allocation failed, allocating 32768 bytes
