
 Thu, 18 Jun 2020 09:06:37 GMT

COMMAND LINE:
 /usr/bin/python2 pidigits.python-2.python 10000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "pidigits.python-2.python", line 10, in <module>
    from gmpy_cffi import mpz
ImportError: No module named gmpy_cffi
