
Wed, 09 Mar 2016 18:00:36 GMT

COMMAND LINE:
/usr/bin/ipy pidigits.ipy-4.ipy 2000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "pidigits.ipy-4.ipy", line 10, in <module>
ImportError: No module named gmpy_cffi
