
Tue, 13 Jun 2017 17:43:35 GMT

COMMAND LINE:
/usr/bin/pypy pidigits.pypy-3.pypy 10000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "pidigits.pypy-3.pypy", line 10, in <module>
    from gmpy import mpz
ImportError: No module named gmpy
