
 Fri, 30 Oct 2020 20:17:24 GMT

COMMAND LINE:
 /usr/bin/python2 pidigits.python-2.python 10000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "pidigits.python-2.python", line 10, in <module>
    from gmpy_cffi import mpz
ImportError: No module named gmpy_cffi
