
Tue, 26 May 2015 13:08:44 GMT

COMMAND LINE:
/usr/bin/jython revcomp.jython-5.jython 0 < revcomp-input1000.txt

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "revcomp.jython-5.jython", line 11, in <module>
    def show(seq, table, write=sys.stdout.buffer.write, nl=b'\n'):
AttributeError: 'file' object has no attribute 'buffer'
