
Wed, 11 Feb 2015 21:17:13 GMT

COMMAND LINE:
/usr/bin/pypy revcomp.pypy-5.pypy 0 < revcomp-input1000.txt

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "revcomp.pypy-5.pypy", line 11, in <module>
    def show(seq, table, write=sys.stdout.buffer.write, nl=b'\n'):
AttributeError: 'file' object has no attribute 'buffer'
